version: "3.9"

services:
  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    networks:
      - data_network
    
  spark-master:
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: "spark-master"
    ports:
      - "7077:7077"  # Spark master port
      - "8081:8080"  # Spark master web UI port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - data_network

  spark-worker-1:
    image: docker.io/bitnami/spark:3.3
    container_name: "spark-worker-1"
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - data_network

  spark-worker-2:
    image: docker.io/bitnami/spark:3.3
    container_name: "spark-worker-2"
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - data_network

  metabase:
    image: metabase/metabase:latest
    container_name: "metabase"
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - data_network

  airflow-webserver: 
    build: ./airflow
    container_name: airflow-webserver
    restart: always
    depends_on:
      - mysql-airflow
    environment:
      - LOAD_EX=n
      - AIRFLOW__CORE__FERNET_KEY=airflow_fernet_key
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow_secret_key
      - AIRFLOW__WEBSERVER__SECRET_KEY_CMD=airflow_secret_key
      - AIRFLOW__WEBSERVER__SECRET_KEY_SECRET=airflow_secret_key
      - AIRFLOW__WEBSERVER__RBAC=False
      - AIRFLOW__WEBSERVER__SESSION_BACKEND=securecookie
      - AIRFLOW_CORE_MYSQL_CONN=mysql+mysqlconnector://airflow:airflow@mysql-airflow:3307/airflow
      - EXECUTOR=Local    
    volumes:
        - ./restaurant_analytis:/usr/local/airflow/restaurant_analytis
        - ./airflow/dags:/usr/local/airflow/dags
        - ./airflow/logs:/usr/local/airflow/logs
        - ./airflow/plugins:/usr/local/airflow/plugins
        - ./airflow/config/airflow.cfg:/usr/local/airflow/config/airflow.cfg
        - ./airflow/jars:/usr/local/airflow/jars
        - ./scripts:/usr/local/airflow/scripts
    ports:
        - "8088:8088"
        - "8888:8888"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
    networks:
        - data_network

networks:
  data_network:
    driver: bridge
    name: data_network